version: '3.9'

services:
  ooc-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ooc-core-app
    command: uvicorn ooc.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/ooc_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    container_name: ooc-core-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ooc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ooc-core-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
